// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mwyzzkbqhzzjmpsptgix.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im13eXp6a2JxaHp6am1wc3B0Z2l4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMwOTkwODcsImV4cCI6MjA1ODY3NTA4N30.2JmZpbN-ivKllLYEdo4Jc475-LSwTRyxLBugdZelIro";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);